
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Usuários</h4>
            </a>
            <a href="/administration/user-new" class="list-group-item">Novo</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Administrador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Sub Administrador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Arbitro</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Concialiador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Mediador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Cidadão</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Advogado/Ente conveniado</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Empresa/Poder público</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Arbitragem</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Valor das causas</h4>
            </a>
            <a href="/administration/" class="list-group-item">Novo</a>
            <a href="/administration/" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Edição do site</h4>
            </a>
            <a href="/administration/" class="list-group-item">Novo</a>
            <a href="/administration/" class="list-group-item">Pesquisar</a>
          </div>

          
        </div><!--/col-md-->
        <div class="col-md-9">
          <div class="jumbotron">
            <h1>Administração</h1>
            <p>Aqui você conseguirá gerenciar usuários, itens dos formulários e todos os itens da administração do sistema, competente ao seu orgão gestor.</p>
          </div>
        </div><!--/col-md-->
      </div><!--/row-->