
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Usuários</h4>
            </a>
            <a href="/administration/user-new" class="list-group-item">Novo</a>
            <a href="/administration/user" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Valor das causas</h4>
            </a>
            <a href="/administration/city-new" class="list-group-item">Novo</a>
            <a href="/administration/city" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Edição do site</h4>
            </a>
            <a href="/administration/pattern-new" class="list-group-item">Novo</a>
            <a href="/administration/pattern" class="list-group-item">Pesquisar</a>
          </div>
        </div><!--/span-->
        <div class="span9">
          <div class="page-header">
            <h1>Pesquisa <small>gerencie aqui os dados dos padrões</small></h1>
            <hr>
            <form class="form-inline" action="/administration/pattern" method="get" role="form">
              <div class="form-group col-md-5">
                <input type="text" class="form-control" placeholder="nome da carroceria" name="field" value="<?=$this->field?>">
              </div>
              <button type="submit" class="btn btn-primary">Pesquisar</button>
            </form>
            <hr>
            <table class="table table-hover table-bordered">
              <thead>
                <th>Nome</th>
                 <th>UVE</th>
              </thead>
              <tbody>
                <?if(is_object($this->list) && !isset($this->list->name)){
                  foreach($this->list as $pattern){?>
                    <tr>
                      <td><a href="/administration/pattern-edit/id/<?=$pattern->id?>"><?=$pattern->name?></a></td>
                      <td><?=$pattern->uve?></td>
                    </tr>
                <?} } else{?>
                  <tr>
                    <td colspan="7">Não encontrado nenhum fiscal na pesquisa.</td>
                  </tr>
                <?}?>
              </tbody>
            </table>
            <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
          </div>
        </div><!--/span-->
      </div><!--/row-->