
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Usuários</h4>
            </a>
            <a href="/administration/user-new" class="list-group-item active">Novo</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Administrador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Sub Administrador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Arbitro</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Concialiador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Mediador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Cidadão</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Advogado/Ente conveniado</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Empresa/Poder público</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Arbitragem</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Valor das causas</h4>
            </a>
            <a href="/administration/" class="list-group-item">Novo</a>
            <a href="/administration/" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Edição do site</h4>
            </a>
            <a href="/administration/" class="list-group-item">Novo</a>
            <a href="/administration/" class="list-group-item">Pesquisar</a>
          </div>
    </div><!--/span-->
    <div class="span9">
      <div class="page-header">
        <h1>Novo Usuário <small>defina aqui os dados do usuário</small></h1>
        <hr>
        <?=$this->form?>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>