
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Usuários</h4>
            </a>
            <a href="/administration/user-new" class="list-group-item">Novo</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Administrador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Sub Administrador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Arbitro</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Concialiador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Mediador</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Cidadão</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Advogado/Ente conveniado</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Empresa/Poder público</a>
            <a href="/administration/user" class="list-group-item">Pesquisar Arbitragem</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Valor das causas</h4>
            </a>
            <a href="/administration/new-valor" class="list-group-item">Novo</a>
            <a href="/administration/valor-causa" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Edição do site</h4>
            </a>
            <a href="/administration/" class="list-group-item">Novo</a>
            <a href="/administration/" class="list-group-item">Pesquisar</a>
          </div>

          
        </div><!--/col-md-->
        <div class="col-md-9">
          <div class="page-header">
            <h1>Pesquisa <small>gerencie aqui os dados dos atendimento</small></h1>
            <hr>
            <form class="form-inline" action="/administration/valor-causa" method="get" role="form">
              <div class="form-group col-md-5">
                <input type="text" class="form-control" placeholder="Número do De" name="field" value="<?=$this->field?>">
              </div>
              <button type="submit" class="btn btn-primary">Pesquisar</button>
            </form>
            <hr>
            <table class="table table-hover table-bordered">
              <thead>
                <th>De</th>
                <th>até</th>
                <th>Taxa de registro</th>
                <th>Taxa de administração</th>
                <th>Honorário</th>
              </thead>
              <tbody>
                <?if(is_object($this->list) && !isset($this->list->name)){
                  foreach($this->list as $body){?>
                    <tr>
                      <td><a href="/administration/valor-causa-edit/id/<?=$body->id?>">R$ <?echo number_format($body->de, 2, ',', '.');?></a></td>
                      <td>
                        <?if($body->ate == 0.00){?>
                          <a href="/administration/valor-causa-edit/id/<?=$body->id?>">Valores Acima</a>
                          <?}else{?>
                          <a href="/administration/valor-causa-edit/id/<?=$body->id?>">R$ <?echo number_format($body->ate, 2, ',', '.');?></a>
                          <?}?>
                      </td>
                      <td ><a href="/administration/valor-causa-edit/id/<?=$body->id?>" >R$ <?echo number_format($body->taxa_registro, 2, ',', '.');?></a></td>
                      <td><a href="/administration/valor-causa-edit/id/<?=$body->id?>">R$ <?echo number_format($body->taxa_adm , 2, ',', '.');?></a></td>
                      <td><a href="/administration/valor-causa-edit/id/<?=$body->id?>">R$ <?echo number_format($body->honorario, 2, ',', '.');?></a></td>

                    </tr>
                <?} } else{?>
                  <tr>
                    <td colspan="7">Não encontrado nenhum fiscal na pesquisa.</td>
                  </tr>
                <?}?>
              </tbody>
            </table>
          
          </div>
        </div><!--/col-md-->
      </div><!--/row-->