<!DOCTYPE html>
<html lang="pt_BR">
  <head>
	  <link href="/css/bootstrap.min.css" rel="stylesheet">
	    <style type="text/css">
	      body {
	        padding-top: 80px;
	      }

	    </style>
	    <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
	    <link href="/css/font-awesome.min.css" rel="stylesheet">
	    <link href="/css/datepicker.css" rel="stylesheet">
	    <link href="/css/general.css" rel="stylesheet">
	    <link href="/css/custom.css" rel="stylesheet">
	    <?if($this->treatment){?>
	    <link href="/css/fullcalendar.css" rel="stylesheet">
	    <link href="/css/fullcalendar.print.css" rel="stylesheet">
	    <?}?>

	    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	    <!--[if lt IE 9]>
	      <script src="/js/html5shiv.js"></script>
	      <script src="/js/respond.min.js"></script>
	    <![endif]-->
  </head>
	<body>
 	<div class="container">
	 <?php echo $this->layout()->content; ?>
	 	<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
    	<div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
          	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        		<div>
          	<iframe width="100%" height="350" src=""></iframe>
        		</div>
      		</div>
    		</div>
  		</div>
		</div>
	</div>
  	<script src="/js/jquery-1.10.1.min.js"></script>
    <script src="/js/jquery.maskedinput.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-datepicker.js"></script>
    <script src="/js/locales/bootstrap-datepicker.pt-BR.js"></script>
    <script src="/js/language/pt-BR.js"></script>
    <script src="/js/d3.v3.min.js"></script>
    <script src="/js/bootstrap3-typeahead.min.js"></script>
    <script src="/js/jquery.typing-0.2.0.min.js"></script>
    <script src="/js/general_2.js"></script>
    <script src="/js/moment.js"></script>
    <?if($this->accident){?>
    <script src="/js/accident.js"></script>
    <?}?>
    <?if($this->treatment){?>
    <script src="/js/fullcalendar.js"></script>
    <script src="/js/gcal.js"></script>
    <script src="/js/jquery.livequery.js"></script>
    <script src="/js/scheduling_v3.js"></script>
    <?}else{?>
    <script src="/js/schedule.js"></script>
    <?}?>
	</body>
</html>