<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/dashboard" class="list-group-item">
          <h4 class="list-group-item-heading">Justiça Alternativa</h4>
        </a>
        <?$authNamespace = new Zend_Session_Namespace('userInformation');
        $institution = $authNamespace->institution; 
        $user = new Application_Model_User();
        $status = $user->validUser($authNamespace->user_id);
        
        if(($institution == 1 || $institution == 4 || $institution == 2 || $institution == 3 || $institution == 5) && $status['status'] == 1){?>
        <a href="/conflicts/types" class="list-group-item active"><i class="fa fa-folder-open"></i> Cadastros<?if($this->allConflicts){?><span class="badge"><?=$this->allConflicts?></span><?}?></a>
        
        <a href="/conflicts/returneds" class="list-group-item"><i class="fa fa-undo"></i> Retornados <?if($this->allReturnedConflicts){?><span class="badge"><?=$this->allReturnedConflicts?></span><?}?></a>
        <a href="/conflicts/accepted" class="list-group-item"><i class="fa fa-check"></i> Aceitos <?if($this->allAcceptedConflicts){?><span class="badge"><?=$this->allAcceptedConflicts?></span><?}?></a>
        <a href="/conflicts/mycases" class="list-group-item"><i class="fa fa-list-ul"></i> Meus casos <?if($this->myCases){?><span class="badge"><?=$this->myCases?></span><?}?></a>
        <?if($institution == 1 || $institution == 4){?>
        <a href="/conflicts/research" class="list-group-item"><i class="fa fa-search"></i> Buscas</a>
        <?}?>
        <?}
        else if($status['status'] == 1){?>
        <a href="/conflicts/mycases" class="list-group-item"><i class="fa fa-list-ul"></i> Meus casos <?if($this->myCases){?><span class="badge"><?=$this->myCases?></span><?}?></a>
        <?}?>
      </div>
    </div>
    <div class="col-md-9">
      <div class="page-header">
        <h1>Cadastro <?php echo $this->type;?> <small>gerencie aqui os dados</small></h1>
        <hr>
        <ul class="nav nav-tabs" id="myTab">
          <li <?if($this->result == 1){?>class="active"<?}?>><a href="#data">Principal</a></li>
          <li <?if($this->result == 2){?>class="active"<?}?>><a href="#data_user">Dados Solicitante</a></li>
          <li <?if($this->result == 3){?>class="active"<?}?>><a href="#data_other_user">Dados da outra parte</a></li>
          <li <?if($this->result == 9){?>class="active"<?}?> ><a href="#documents">Documentos</a></li>     
          <li <?if($this->result == 10){?>class="active"<?}?> ><a href="#reunions">Reuniões</a></li>   
          <li <?if($this->result == 11){?>class="active"<?}?> ><a href="#historic">Histórico</a></li>     
        </ul>
        <div class="tab-content">
          <div class="tab-pane <?if($this->result == 1){?>active<?}?>" id="data">
            <hr>
            <?echo $this->mainForm;?>
          </div>
          <div class="tab-pane <?if($this->result == 2){?>active<?}?>" id="data_user">
            <hr>
            <?=$this->dataUserForm?>
          </div>
          <div class="tab-pane <?if($this->result == 3){?>active<?}?>" id="data_other_user">
            <hr>
            <?echo $this->dataOtherUserForm;?>
          </div>

          <div class="tab-pane <?if($this->result == 9){?>active<?}?>" id="documents">
            <hr>
            <div class="panel-group" id="accordion">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#crlv">
                      Documento
                    </a>
                  </h4>
                </div>
                <div id="crlv" class="panel-collapse collapse">
                  <div class="panel-body">
                    <?$conflict = new Application_Model_Conflict(); 
                    $document = $conflict->returnDocument($this->conflictId,'doc');
                    foreach ($document as $doc) {
                        $documents = $doc->document;
                    }
                    if(empty($documents)){
                        echo "Documento não anexado!";
                    }
                    else{
                      ?>               
                       <a href="/upload/conflitos/<?=$this->conflictId?>/<?=$documents?>" class="btn btn-default" target="_blank">
                        <span class="glyphicon glyphicon-download"></span> Download
                      </a>
                    <?}?>
                  </div>
                </div>
              </div>
            </div>  
          </div> 

          <div class="tab-pane <?if($this->result == 10){?>active<?}?>" id="reunions">
            <hr>
            <div class="panel-group" id="accordion">
              Para visualizar sua agenda e gerenciar seus horarios <a href="http://onibus/scheduling/treatment" target="_blank">click aqui</a>.
              <br><br>
              Para acessar o Whatsapp Web para reunir ou conversar com o cliente <a href="https://web.whatsapp.com/" target="_blank">click aqui</a>.
              <br><br>
              Para acessar o Skype Web para reunir ou conversar com o cliente <a href="https://login.skype.com/login" target="_blank">click aqui</a>.
              <br><br>   
              Para fazer download do Skype desktop para reunir ou conversar com o cliente <a href="https://www.skype.com/pt-br/" target="_blank">click aqui</a>.
              <br><br> 
              Para agendar uma reunião com o cliente <a href="/agendamento/index/id/<?=$this->conflictId?>" target="_blank">click aqui</a>.
            </div>  
          </div> 

          <div class="tab-pane <?if($this->result == 11){?>active<?}?>" id="historic">
            <hr>
            <form action="/conflicts/save-status" method="post">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group" aria-required="true">
                      <label class="select control-label"> Status </label>
                      <select class="select form-control" id="conflict_status" name="conflict_status">
                        <option value="0">Selecione</option>
                        <option value="1">Acordado</option>
                        <option value="2">Aguardando aceite de minuta</option>
                        <option value="3">Aguardando homologação</option>
                        <option value="4">Concluído/Sem homologação</option>
                        <option value="5">Concluído/homologado</option>
                        <option value="6">Em andamento</option>
                        <option value="7">Encaminhado para audiência presencial</option>
                        <option value="8">Enviado para homologação</option>
                        <option value="9">Mediação / Árbitragem encerrada por inatividade da parte requerente</option>
                        <option value="10">Mediação / Árbitragem encerrada por inatividade da parte requerida</option>
                        <option value="11">Mediação / Árbitragem encerrada por inatividade do operador do sistema</option>
                        <option value="12">Minuta confirmada</option>
                        <option value="13">Minuta recusada</option>
                        <option value="14">Retornado</option>
                        <option value="15">Solicitada homologação presencial</option>
                        <option value="16">Solicitada mediação presencial</option>
                    </select>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-10">
                  <div class="form-group">
                    <label class="string control-label" aria-required="true"> Descreva as observações deste status.</label>
                    <br>
                    <textarea class="string form-control" id="desc_status" name="desc_status" cols="100" rows="9"></textarea>
                  </div>
                </div> 
              </div>
              <div class="row text-right">
                <input type="hidden" name="conflictId" value="<?=$this->conflictId?>">
                <button type="submit" class="btn btn-success">Salvar Status</button>
                <a class="btn btn-success" data-toggle="modal" data-target="#returned_case">Retornar caso</a>           
              </div>
            </form>

            <br>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <table class="table table-hover table-bordered">
                    <thead>
                      <th>Termo de autenticidade</th>
                      <th>Nome Responsável</th>
                      <th>Data</th>
                      <th>Status</th>
                      <th>Observações</th>
                    </thead>
                    <tbody>
                      <?if(count($this->allConflictHistoric)){
                        foreach($this->allConflictHistoric as $body){?>
                          <tr>
                            <td><?=$body->id_historic?></td>
                            <td><?=$body->name?></td>
                            <td><?=Application_Model_General::dateToBr($body->date)?></td>
                            <td><?=$body->nome?></td>
                            <td><?=$body->desc?></td>
                          </tr>
                          <?} // FIM do foreach($this->list as $body)
                        } // FIM do if(count($this->list))          
                      else{?>
                        <tr>
                          <td colspan="5"><h4>Não existe historico deste conflito.</h4></td>
                        </tr>
                      <?}?>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
      <div class="row text-right">
        <?php if($authNamespace->institution == 1 || $authNamespace->institution == 4){?>
          <a class="btn btn-success" data-toggle="modal" data-target="#accept_case">Encaminhar este caso</a>
        <?}
        else{?>
          <a class="btn btn-success" data-toggle="modal" data-target="#accept_case_user">Aceitar este caso</a>
        <?}?>
      </div>
    </div><!--/col-md-->

  </div><!--/row-->
</div><!--/container-->

<form action="/conflicts/accept-case" method="post">
  <div class="modal fade" id="accept_case" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Encaminhar o caso</h4>
        </div>
        <div class="modal-body">
          <h4>Para qual grupo encaminhar este caso?</h4>
          <div class="checkbox">
            <label>
              <input type="radio" name="grupo" id="grupo" value="1"> Mediador
            </label>
            <br>
            <label>
              <input type="radio" name="grupo" id="grupo" value="2"> Conciliador
            </label>
            <br>
            <label>
              <input type="radio" name="grupo" id="grupo" value="3"> Árbitro
            </label>
          </div>
        </div>
        <div class="modal-footer">
          <input type="hidden" name="conflictId" value="<?=$this->conflictId?>">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <button type="submit" class="btn btn-success">Encaminhar</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>

<form action="/conflicts/returneds" method="post">
  <div class="modal fade" id="returned_case" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Retornar o caso</h4>
        </div>
        <div class="modal-body">
          <h4>Retornar este caso para o grupo?</h4>
        </div>
        <div class="modal-footer">
        <!-- retornar para o grupo do usuario que estava com aquele caso -->
          <input type="hidden" name="conflictId" value="<?=$this->conflictId?>">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <button type="submit" class="btn btn-success">Retornar</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>

<form action="/conflicts/accept-case-user" method="post">
  <div class="modal fade" id="accept_case_user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Aceitar o caso</h4>
        </div>
        <div class="modal-body">
          <h4>Tem certeza que desja aceitar este caso?</h4>
        <div class="modal-footer">
          <input type="hidden" name="conflictId" value="<?=$this->conflictId?>">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <button type="submit" class="btn btn-success">Aceitar</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>
