<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/dashboard" class="list-group-item">
          <h4 class="list-group-item-heading">Justiça Alternativa</h4>
        </a>
        <?$authNamespace = new Zend_Session_Namespace('userInformation');
        $institution = $authNamespace->institution; 
        $user = new Application_Model_User();
        $status = $user->validUser($authNamespace->user_id);
         
        if(($institution == 1 || $institution == 4 || $institution == 2 || $institution == 3 || $institution == 5) && $status['status'] == 1){?>
        <a href="/conflicts/types" class="list-group-item active"><i class="fa fa-folder-open"></i> Cadastros<?if($this->allConflicts){?><span class="badge"><?=$this->allConflicts?></span><?}?></a>

        <a href="/conflicts/returneds" class="list-group-item"><i class="fa fa-undo"></i> Retornados</a>
        <a href="/conflicts/accepted" class="list-group-item"><i class="fa fa-check"></i> Aceitos <?if($this->allAcceptedConflicts){?><span class="badge"><?=$this->allAcceptedConflicts?></span><?}?></a>
        <a href="/conflicts/mycases" class="list-group-item"><i class="fa fa-list-ul"></i> Meus casos</a>

        <?if($institution == 1 || $institution == 4){?>
        <a href="/conflicts/research" class="list-group-item"><i class="fa fa-search"></i> Buscas</a>
        <?}
        }
        else if($status['status'] == 1){?>
        <a href="/conflicts/mycases" class="list-group-item"><i class="fa fa-list-ul"></i> Meus casos</a>
        <?}?>
      </div>
    </div>
    <div class="col-md-9">
      <div class="page-header">
        <h1>Cadastro <?php echo $this->type ?> <small>gerencie aqui os dados</small></h1>
        <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Nome Solicitante</th>
            <th>Nome outra parte</th>
            <th>Descrição do conflito</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <?if(count($this->list)){
              foreach($this->list as $body){?>
                <tr>
                  <td><?=$body->name?></td>
                  <td><?=$body->name?></td>
                  <td><?=$body->desc_conflict?></td>
                  <td>                                                            
                      <a href="/conflicts/edit/id/<?=$body->id_conflict?>/type/<?=$this->type?>" class="btn btn-default btn-sm help" title="Visualizar dados do conflito"><i class="fa fa-eye"></i></a>                     
                  </td>
                </tr>
                <?} // FIM do foreach($this->list as $body)
              } // FIM do if(count($this->list))          
            else{?>
              <tr>
                <td colspan="7"><h4>Não há conflitos cadastrados.</h4></td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div><!--/span-->
  </div>
</div>



<div id="block_msg_modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Justificativa Status</h4>
      </div>
      <div class="modal-body">
        <textarea id="jus_block_textarea" class="form-control" rows="4" cols="10"></textarea>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
