<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/scheduling" class="list-group-item">
          <h4 class="list-group-item-heading">Agendamento</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos atendimentos</p>
        </a>
        <a href="/scheduling/treatment" class="list-group-item"><span class="glyphicon glyphicon-calendar"></span> Calendário</a>
        <a href="/scheduling/calendar" class="list-group-item"><span class="glyphicon glyphicon-book"></span> Recessos</a>
        <a href="/scheduling/hour" class="list-group-item"><span class="glyphicon glyphicon-saved"></span> Horários</a>
        <a href="/scheduling/print" class="list-group-item"><span class="glyphicon glyphicon-search"></span> Buscar</a>
        <!-- <a href="/scheduling/report" class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a> -->
        <!-- <a href="/scheduling/graphic" class="list-group-item"><span class="glyphicon glyphicon-picture"></span> Gráfico</a> -->
      </div>
    </div><!--/col-md-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página Inicial</a></li>
        <li class="active">Agendamento</li>
      </ol>  
      <div class="well">
        <img class="img-responsive img-thumbnail" src="/img/scheduling.jpg"><br><br>
        <h1>Agendamento</h1>
        <p>Este é o agendamento online das reuniões marcadas pelos membros do Justiça Alternativa.</p>
      </div>
    </div>
  </div>
</div>